---
- name: Provision NetOrion VM
  hosts: all
  become: yes
  vars_files:
    - "{{ inventory_dir }}/../vars/all.yml"
  roles:
    - common
    - redis
    - dpdk
    - libl2fwd
    - ntopng
    - netorion
