- name: Ensure build directory exists
  file:
    path: "{{ netorion_build_dir }}"
    state: directory
    owner: "{{ netorion_user }}"
    group: "{{ netorion_user }}"
    mode: '0755'
  become: yes

- name: Clone nDPI repository
  git:
    repo: https://github.com/ntop/nDPI.git
    dest: "{{ netorion_build_dir }}/nDPI"
    version: "{{ ndpi_branch }}"
  register: ndpi_clone
  become: yes
  become_user: "{{ netorion_user }}"

- name: Build nDPI
  shell: |
    cd "{{ netorion_build_dir }}/nDPI"
    ./autogen.sh
    ./configure
    make -j$(nproc)
  become: yes
  become_user: "{{ netorion_user }}"

- name: Clone ntopng repository
  git:
    repo: https://github.com/rdev0x1/ntopng-dpdk.git
    dest: "{{ netorion_build_dir }}/ntopng"
    version: "{{ ntopng_branch }}"
  register: ntopng_clone
  become: yes
  become_user: "{{ netorion_user }}"

- name: Build ntopng
  shell: |
    cd "{{ netorion_build_dir }}/ntopng"
    ./autogen.sh
    ./configure
    make -j$(nproc)
  become: yes
  become_user: "{{ netorion_user }}"
