---

- name: Install ntopng development tools
  apt:
    name:
      - libxml2-dev
      - libpcap-dev
      - libtool
      - libtool-bin
      - rrdtool
      - librrd-dev
      - wget
      - libsqlite3-dev
      - libhiredis-dev
      - libmaxminddb-dev
      - libcurl4-openssl-dev
      - libpango1.0-dev
      - libcairo2-dev
      - libnetfilter-queue-dev
      - zlib1g-dev
      - libssl-dev
      - libcap-dev
      - libnetfilter-conntrack-dev
      - libreadline-dev
      - libjson-c-dev
      - libldap2-dev
      - rename
      - libsnmp-dev
      - libexpat1-dev
      - libmaxminddb-dev
      - libradcli-dev
      - libjson-c-dev
      - libzmq3-dev
      - curl
      - jq
      - libgcrypt20-dev
    state: present

- name: Install ntopng dependencies
  apt:
    name:
      - net-tools
    state: present

- name: Install package build tools
  apt:
    name:
      - debhelper
      - dkms
    state: present

- name: Install requirements for debian 12
  apt:
    name:
      - debsigs
    state: present

- name: Install MariaDB
  apt:
    name:
        - libpng-dev
        - libzmq5-dev
        - default-libmysqlclient-dev
        - libgcrypt20-dev
    state: present

- name: Include build tasks for nDPI and ntopng
  include_tasks: build.yml
